"""Public execution host contract consumed by the agent application."""

from __future__ import annotations

from typing import Any, Protocol

from voidx.agent.domain.state import AgentRuntime
from voidx.agent.domain.turn import TurnPhase
from voidx.config import Config, Settings
from voidx.memory.service import SessionInfo
from voidx.runtime.intent import InteractionMode
from voidx.runtime.task_state import TaskState


class ExecutionHost(Protocol):
    """Public interface required by application services and turn adapters."""

    config: Config
    model: Any

    @property
    def ui(self) -> Any: ...

    @property
    def runtime_guards(self) -> Any: ...

    @property
    def workspace(self) -> str: ...

    @property
    def settings(self) -> Settings | None: ...

    @property
    def session(self) -> SessionInfo | None: ...

    @property
    def permission(self) -> Any: ...

    @property
    def mcp_manager(self) -> Any: ...

    @property
    def lsp_manager(self) -> Any: ...

    @property
    def app(self) -> Any: ...

    @app.setter
    def app(self, value: Any) -> None: ...

    @property
    def usage_stats(self) -> Any: ...

    @property
    def debug_enabled(self) -> bool: ...

    @property
    def plan_mode(self) -> bool: ...

    @property
    def slash(self) -> Any: ...

    @property
    def gateway_session(self) -> Any: ...

    @gateway_session.setter
    def gateway_session(self, value: Any) -> None: ...

    @property
    def any_messages_sent(self) -> bool: ...

    @any_messages_sent.setter
    def any_messages_sent(self, value: bool) -> None: ...

    @property
    def interaction_mode(self) -> InteractionMode: ...

    @property
    def task_state(self) -> TaskState: ...

    @property
    def compaction_summary(self) -> str: ...

    @property
    def session_date(self) -> str: ...

    async def run_turn(self, user_text: str, *, display_text: str | None = None, context: Any = None) -> None: ...
    async def restore_runtime_state(self) -> None: ...
    async def apply_settings_update(self, settings: Settings) -> None: ...
    async def restore_transcript_snapshot(self, *, append: bool = False) -> bool: ...
    async def delete_empty_current_session(self) -> None: ...
    async def clear_current_session(self) -> None: ...
    async def resume_session(self, session: SessionInfo) -> None: ...
    async def set_session_title(self, title: str) -> None: ...
    async def persist_runtime_state(self) -> None: ...
    async def compact_session_history(self, *, force: bool = True) -> bool: ...
    def bind_startup_presenter(self, presenter: Any) -> None: ...
    async def show_startup(self, *, append_transcript: bool = False, prefer_direct: bool = False) -> None: ...
    def set_interaction_mode(self, mode: str | InteractionMode) -> InteractionMode: ...
    def set_task_state(self, task_state: TaskState) -> None: ...
    def set_compaction_summary(self, value: str) -> None: ...
    def set_session_date(self, value: str) -> None: ...
    def runtime_snapshot(self) -> AgentRuntime: ...
    def set_debug(self, value: bool) -> None: ...
    def submit_guidance(self, text: str, **kwargs: Any) -> bool: ...
    def dispatch(self, inp: Any) -> Any: ...
