"""Narrow Agent persistence ports implemented by persistence adapters."""

from __future__ import annotations

from typing import Any, Awaitable, Callable, Protocol

from voidx.agent.domain.profile import RuntimeProfile
from voidx.agent.domain.state import SessionRuntimeState
from voidx.agent.domain.thread import AgentThread, AgentThreadState, RuntimeOutboxItem, ThreadAttempt


class ThreadStateConflict(RuntimeError):
    """Raised when an optimistic state-version update loses the race."""


class SessionRepository(Protocol):
    """Presentation-facing session CRUD operations."""

    async def create_session(self, workspace: str = ".", provider: str = "anthropic", model: str = "", **kwargs: object) -> Any: ...
    async def get_session(self, session_id: str) -> Any | None: ...
    async def list_sessions(self, limit: int = 50) -> list[Any]: ...
    async def fork_session(self, session_id: str, *, title: str | None = None) -> Any | None: ...
    async def delete_session(self, session_id: str) -> None: ...
    async def update_title(self, session_id: str, title: str) -> None: ...
    async def update_session_model(self, session_id: str, provider: str, model: str) -> None: ...
    async def update_session_profile(self, session_id: str, profile: str) -> None: ...
    async def stage_provisional_session(self, **kwargs: object) -> Any: ...
    async def promote_provisional_session(self, session_id: str) -> int: ...
    async def rollback_provisional_session(self, session_id: str) -> int: ...
    async def initialize_provisional_owner(self, owner_id: str) -> list[str]: ...
    async def close_provisional_owner(self, owner_id: str) -> int: ...


class SessionCleanup(Protocol):
    """Slash-facing session deletion planning operations."""

    async def plan_session_delete(self, scope: str = "30d", **kwargs: object) -> Any: ...
    async def apply_session_delete_plan(self, plan: Any) -> int: ...


SessionCreator = Callable[..., Awaitable[Any]]


class ThreadStore(Protocol):
    """Application-facing contract for durable thread, attempt, and outbox state."""

    async def create_thread(self, thread: AgentThread, *, profile: RuntimeProfile, state: AgentThreadState | None = None, resource_scope: dict[str, Any] | None = None) -> Any: ...
    async def load(self, thread_id: str) -> Any | None: ...
    async def save_state(self, thread_id: str, state: AgentThreadState, *, expected_state_version: int) -> Any: ...
    async def ensure_session(self, session_id: str, workspace: str, *, profile: str = "coding", title: str = "Loop session", root_session_id: str | None = None) -> None: ...


class ThreadRepository(Protocol):
    async def create_thread(self, thread: AgentThread, *, profile: RuntimeProfile, state: AgentThreadState | None = None, resource_scope: dict[str, Any] | None = None) -> Any: ...
    async def load(self, thread_id: str) -> Any | None: ...


class AttemptRepository(Protocol):
    async def begin_attempt(self, thread_id: str, *, expected_state_version: int, source_outbox_id: str, input_frame: dict[str, Any], lease_owner: str, lease_seconds: float) -> ThreadAttempt: ...


class OutboxRepository(Protocol):
    async def claim_next_outbox(self, *, lease_owner: str, lease_seconds: float, kind: str | None = None, thread_id_prefix: str | None = None, exclude_outbox_ids: set[str] | None = None) -> RuntimeOutboxItem | None: ...


class RuntimeStateRepository(Protocol):
    async def load_runtime_state(self, session_id: str) -> SessionRuntimeState: ...
    async def save_runtime_state(self, session_id: str, snapshot: SessionRuntimeState) -> None: ...


class ProfileRepository(Protocol):
    async def list(self) -> list[Any]: ...
    async def get(self, name: str) -> Any | None: ...
    async def save(self, profile: Any) -> None: ...
    async def delete(self, name: str) -> None: ...
