"""Narrow Agent persistence ports implemented by persistence adapters."""

from __future__ import annotations

from typing import Any, Awaitable, Callable, Protocol

from voidx.agent.domain.agent_profile import ResolvedAgentProfile
from voidx.agent.domain.profile import RuntimeProfile
from voidx.agent.domain.state import SessionRuntimeState
from voidx.agent.domain.thread import AgentThread, AgentThreadState, RuntimeOutboxItem, ThreadAttempt


class ThreadStateConflict(RuntimeError):
    """Raised when an optimistic state-version update loses the race."""


class GoalProtocolConflict(RuntimeError):
    """Raised when a Goal journal position cannot be accepted safely."""


class GoalRuntimeCorruption(RuntimeError):
    """Raised for deterministic Goal journal, state, or transcript corruption."""

    def __init__(
        self,
        reason: str,
        *,
        observed_sequence: int = -1,
        evidence: tuple[str, ...] = (),
    ) -> None:
        super().__init__(reason)
        self.observed_sequence = observed_sequence
        self.evidence = evidence


class GuidanceConflict(RuntimeError):
    """Raised when a durable Guidance identity is reused with different data."""


class SessionRepository(Protocol):
    """Presentation-facing session CRUD operations."""

    async def create_session(self, workspace: str = ".", provider: str = "anthropic", model: str = "", **kwargs: object) -> Any: ...
    async def get_session(self, session_id: str) -> Any | None: ...
    async def list_sessions(self, limit: int = 50) -> list[Any]: ...
    async def fork_session(self, session_id: str, *, title: str | None = None) -> Any | None: ...
    async def delete_session(self, session_id: str) -> None: ...
    async def update_title(self, session_id: str, title: str) -> None: ...
    async def update_session_model(self, session_id: str, provider: str, model: str) -> None: ...
    async def update_session_profile(self, session_id: str, profile: str, *, profile_snapshot: Any | None = None) -> None: ...
    async def stage_provisional_session(self, **kwargs: object) -> Any: ...
    async def promote_provisional_session(self, session_id: str) -> int: ...
    async def rollback_provisional_session(self, session_id: str) -> int: ...
    async def initialize_provisional_owner(self, owner_id: str) -> list[str]: ...
    async def close_provisional_owner(self, owner_id: str) -> int: ...


class SessionCleanup(Protocol):
    """Slash-facing session deletion planning operations."""

    async def plan_session_delete(self, scope: str = "30d", **kwargs: object) -> Any: ...
    async def apply_session_delete_plan(self, plan: Any) -> int: ...


SessionCreator = Callable[..., Awaitable[Any]]


class ThreadStore(Protocol):
    """Application-facing contract for durable thread, attempt, and outbox state."""

    async def create_thread(self, thread: AgentThread, *, profile: ResolvedAgentProfile | RuntimeProfile, state: AgentThreadState | None = None, resource_scope: dict[str, Any] | None = None) -> Any: ...
    async def load(self, thread_id: str) -> Any | None: ...
    async def save_state(self, thread_id: str, state: AgentThreadState, *, expected_state_version: int) -> Any: ...
    async def submit_guidance(self, guidance: Any) -> Any: ...
    async def get_guidance(self, guidance_id: str) -> Any | None: ...
    async def bind_guidance(self, delivery_id: str, *, session_id: str = "", thread_id: str = "", run_id: str = "", phase: str | None = None) -> list[Any]: ...
    async def release_guidance(self, delivery_id: str) -> None: ...
    async def consume_guidance(self, delivery_id: str) -> None: ...
    async def submit_goal_protocol(self, record: Any, *, attempt_id: str = "", lease_owner: str = "", fencing_token: int = 0) -> Any: ...
    async def commit_goal_phase(self, *, attempt_id: str, protocol_id: str, lease_owner: str, fencing_token: int, guidance_delivery_id: str = "") -> Any: ...
    async def commit_goal_needs_resume(self, *, attempt_id: str, phase: str, reason: str, lease_owner: str, fencing_token: int, guidance_delivery_id: str = "") -> Any: ...
    async def get_goal_protocol(self, protocol_id: str) -> Any | None: ...
    async def list_goal_protocols(self, generation: str) -> list[Any]: ...
    async def project_goal_protocol(self, protocol_id: str) -> Any: ...
    async def get_goal_generation(self, generation: str) -> Any | None: ...
    async def get_goal_runtime_failure(self, generation: str) -> Any | None: ...
    async def fail_goal_generation(self, failure: Any) -> Any: ...
    async def list_goal_public_summaries(self, main_session_id: str) -> list[dict[str, Any]]: ...
    async def list_pending_goal_public_summaries(self, *, main_session_id: str = "", generation: str = "") -> list[dict[str, Any]]: ...
    async def deliver_goal_public_summary(self, summary_id: str) -> bool: ...
    async def deliver_goal_public_summaries(self, *, main_session_id: str = "", generation: str = "") -> int: ...
    async def archive_goal_generation(self, generation: str) -> Any: ...
    async def cleanup_goal_generation(self, generation: str) -> Any: ...
    async def list_goal_generations(self, main_session_id: str) -> list[Any]: ...
    async def prepare_goal_generation_cleanup(self, generation: str, *, reason: str) -> Any: ...
    async def prepare_orphan_goal_generation_cleanups(self) -> list[str]: ...
    async def list_goal_cleanup_tombstones(self) -> list[dict[str, Any]]: ...
    async def reconcile_goal_cleanup(self, generation: str) -> Any: ...
    async def ensure_goal_phase_outbox(self, generation: str) -> Any | None: ...
    async def acquire_goal_generation_lease(self, generation: str, lease_owner: str, *, lease_seconds: float) -> bool: ...
    async def renew_goal_generation_lease(self, generation: str, lease_owner: str, *, lease_seconds: float) -> bool: ...
    async def release_goal_generation_lease(self, generation: str, lease_owner: str) -> bool: ...
    async def get_goal_generation_lease(self, generation: str) -> dict[str, Any] | None: ...
    async def ensure_session(self, session_id: str, workspace: str, *, profile: str = "coding", title: str = "Loop session", root_session_id: str | None = None, profile_snapshot: Any | None = None) -> None: ...
    async def get_session(self, session_id: str) -> Any | None: ...


class ThreadRepository(Protocol):
    async def create_thread(self, thread: AgentThread, *, profile: ResolvedAgentProfile | RuntimeProfile, state: AgentThreadState | None = None, resource_scope: dict[str, Any] | None = None) -> Any: ...
    async def load(self, thread_id: str) -> Any | None: ...


class AttemptRepository(Protocol):
    async def begin_attempt(self, thread_id: str, *, expected_state_version: int, source_outbox_id: str, input_frame: dict[str, Any], lease_owner: str, lease_seconds: float) -> ThreadAttempt: ...


class OutboxRepository(Protocol):
    async def claim_next_outbox(self, *, lease_owner: str, lease_seconds: float, kind: str | None = None, thread_id_prefix: str | None = None, exclude_outbox_ids: set[str] | None = None) -> RuntimeOutboxItem | None: ...


class RuntimeStateRepository(Protocol):
    async def load_runtime_state(self, session_id: str) -> SessionRuntimeState: ...
    async def save_runtime_state(self, session_id: str, snapshot: SessionRuntimeState) -> None: ...


class ProfileRepository(Protocol):
    async def list(self) -> list[Any]: ...
    async def get(self, name: str) -> Any | None: ...
    async def save(self, profile: Any) -> None: ...
    async def delete(self, name: str) -> None: ...
