"""Narrow Agent persistence ports implemented by persistence adapters."""

from __future__ import annotations

from typing import Any, Protocol

from voidx.agent.domain.profile import RuntimeProfile
from voidx.agent.domain.thread import AgentThread, AgentThreadState, RuntimeOutboxItem, ThreadAttempt


class SessionRepository(Protocol):
    async def get(self, session_id: str) -> Any | None: ...
    async def create(self, workspace: str, **kwargs: object) -> Any: ...


class ThreadRepository(Protocol):
    async def create_thread(self, thread: AgentThread, *, profile: RuntimeProfile, state: AgentThreadState | None = None, resource_scope: dict[str, Any] | None = None) -> Any: ...
    async def load(self, thread_id: str) -> Any | None: ...


class AttemptRepository(Protocol):
    async def begin_attempt(self, thread_id: str, *, expected_state_version: int, source_outbox_id: str, input_frame: dict[str, Any], lease_owner: str, lease_seconds: float) -> ThreadAttempt: ...


class OutboxRepository(Protocol):
    async def claim_next_outbox(self, *, lease_owner: str, lease_seconds: float, kind: str | None = None, thread_id_prefix: str | None = None, exclude_outbox_ids: set[str] | None = None) -> RuntimeOutboxItem | None: ...


class RuntimeStateRepository(Protocol):
    async def load_runtime_state(self, session_id: str) -> Any: ...
    async def save_runtime_state(self, session_id: str, snapshot: Any) -> None: ...


class ProfileRepository(Protocol):
    async def list(self) -> list[Any]: ...
    async def get(self, name: str) -> Any | None: ...
    async def save(self, profile: Any) -> None: ...
    async def delete(self, name: str) -> None: ...
