"""Mutable permission state boundary owned by an adapter."""

from __future__ import annotations

from typing import AsyncContextManager, Protocol

from voidx.tooling.domain.grants import AccessGrant
from voidx.tooling.ports.authorization import ExecutionLease


class PermissionState(Protocol):
    state_revision: int
    permissions_revision: int
    revocation_epoch: int
    ai_approval_count: int

    def session_rules(self) -> tuple[frozenset[str], frozenset[str]]: ...
    def set_session_rule(self, tool: str, *, allow: bool) -> None: ...
    def has_active_leases(self) -> bool: ...
    def advance_state(self, *, permissions: bool = False, revoke: bool = False) -> None: ...
    def grants_snapshot(self) -> tuple[AccessGrant, ...]: ...
    def add_grant(self, grant: AccessGrant) -> bool: ...
    def clear_runtime_grants_and_advance(self) -> None: ...
    def clear_session_permissions(self) -> bool: ...
    def increment_ai_approval_count(self) -> None: ...
    def set_ai_approval_count(self, value: int) -> None: ...
    def commit_guard(self) -> AsyncContextManager[None]: ...
    async def acquire_grant_targets(self, paths, *, final_paths=None) -> object: ...
    def acquire_execution_lease(self) -> ExecutionLease: ...
    def has_active_execution_lease(self, lease: ExecutionLease) -> bool: ...
    def release_execution_lease(self, lease: ExecutionLease) -> None: ...
