"""Narrow use-case capability contracts consumed by slash commands."""

from __future__ import annotations

from typing import Protocol




class PromptUi(Protocol):
    status: object
    async def ask_choice(self, prompt: str, choices: list[object], **kwargs: object) -> object: ...
    async def ask_text(self, prompt: str, **kwargs: object) -> str | None: ...


class UiState(Protocol):
    session_tracker: object
    def get_dock(self) -> object | None: ...


class ModelConfigView(Protocol):
    model: object


class UserConfigView(Protocol):
    user_profile: object


class ModelSettingsOps(Protocol):
    async def list_profiles(self) -> list[object]: ...
    async def resolve_api_key(self, provider: str) -> str | None: ...
    async def resolve_base_url(self, provider: str) -> str | None: ...
    async def resolve_profile(self, name: str | None = None) -> object | None: ...
    async def resolve_protocol(self, provider: str) -> str | None: ...
    async def save_profile(self, profile: object, **kwargs: object) -> object: ...
    async def delete_profile(self, name: str, **kwargs: object) -> object: ...
    def list_custom_providers(self) -> list[object]: ...
    def _set_setting(self, name: str, value: object) -> object: ...
    def _pop_setting(self, name: str) -> object: ...


class IntegrationSettingsOps(Protocol):
    def get_tavily_api_key(self) -> str | None: ...
    def get_mcp_server(self, name: str) -> object | None: ...
    def list_mcp_servers(self) -> list[object]: ...
    def delete_mcp_server(self, name: str) -> object: ...
    def save_mcp_server(self, server: object) -> object: ...
    def set_mcp_server_auto(self, name: str, enabled: bool) -> object: ...
    def set_mcp_server_disabled(self, name: str, disabled: bool) -> object: ...
    def set_skill_auto(self, name: str, enabled: bool) -> object: ...
    def set_skill_enabled(self, name: str, enabled: bool) -> object: ...
    def set_tavily_api_key(self, value: str) -> object: ...
    def delete_tavily_api_key(self) -> object: ...
    def set_web_tool_route(self, kind: str, route: object) -> object: ...
    def clear_web_routes_for_server(self, name: str, **kwargs: object) -> object: ...


class PermissionOps(Protocol):
    permission_mode: str
    def allow(self, pattern: str) -> None: ...
    def deny(self, pattern: str) -> None: ...
    def set_permission_mode(self, mode: str) -> None: ...
    def show_rules(self) -> str: ...


class LspOps(Protocol):
    initializing: bool
    initialized: bool
    servers: dict[str, object]
    def statuses(self) -> list[object]: ...
    def doctor(self) -> list[object]: ...
    async def restart(self, language: str | None = None) -> None: ...


class McpOps(Protocol):
    started: bool
    def statuses(self) -> list[object]: ...
    async def restart_all(self) -> None: ...
    async def list_tools_for_server(self, name: str) -> list[object]: ...


class ModelCatalogOps(Protocol):
    async def list_models(self, provider: str) -> list[object]: ...
    async def list_models_for_config(self, model_config: object) -> list[object]: ...
    def list_fallback_models(self, provider: str) -> list[object]: ...


class SkillsOps(Protocol):
    service: object


class UpdateOps(Protocol):
    async def check_for_update(self) -> object: ...
    def is_newer(self, latest: str) -> bool: ...
    async def perform_upgrade(self, version: str | None = None) -> object: ...
    def upgrade_hint(self) -> str: ...
class AutomationSlashPort(Protocol):
    ui: object
    goal_service: object | None
    loop_service: object | None
    session: object | None
    workspace: str
    def can_submit_guidance(self) -> bool: ...
    def submit_guidance(self, text: str, **kwargs: object) -> bool: ...
    def interaction_mode_value(self) -> str: ...
    async def run_coding_turn(self, text: str, *, display_text: str | None = None) -> object: ...




class LogConfigView(Protocol):
    log_llm_exchange: bool
    log_llm_diagnostic: bool
class ModeSlashPort(Protocol):
    ui: object
    ui_state: UiState
    clipboard_image: object
    goal_service: object | None
    session: object | None
    usage_stats: object
    workspace: str
    log_config: LogConfigView
    async def clear_current_session(self) -> None: ...
    def debug_enabled(self) -> bool: ...
    def interaction_mode_value(self) -> str: ...
    def set_debug(self, value: bool) -> None: ...
    def set_interaction_mode(self, mode: object) -> None: ...


class SessionSlashPort(Protocol):
    ui: object
    ui_state: UiState
    prompt_ui: PromptUi | None
    model_config: ModelConfigView
    session: object | None
    workspace: str
    async def regenerate_session_title(self) -> bool: ...
    async def restore_transcript_snapshot(self, *, append: bool = False) -> bool: ...
    async def resume_session(self, session: object) -> None: ...
    async def set_session_title(self, title: str) -> bool: ...
    async def show_startup(self, *, prefer_direct: bool = False) -> None: ...


class ModelSlashPort(Protocol):
    ui: object
    prompt_ui: PromptUi | None
    api_key: str | None
    compaction: object | None
    model_config: ModelConfigView
    model: object | None
    model_catalog_ops: ModelCatalogOps
    provider_specs: object
    reasoning_effort_type: object
    session: object | None
    model_settings: ModelSettingsOps
    usage_stats: object
    def context_limit_resolver(self, provider: str, protocol: str, context_window: int | None) -> int: ...
    def model_factory(self, api_key: str, model_config: ModelConfigView) -> object: ...


class IntegrationsSlashPort(Protocol):
    ui: object
    prompt_ui: PromptUi | None
    lsp_ops: LspOps | None
    mcp_ops: McpOps | None
    integration_settings: IntegrationSettingsOps
    skills_ops: SkillsOps
    workspace: str
    def invalidate_skill_service_cache(self) -> None: ...


class PreferencesSlashPort(Protocol):
    ui: object
    prompt_ui: PromptUi | None
    user_config: UserConfigView
    model_config: object
    reasoning_effort_type: object
    language_labels: object
    permission_ops: PermissionOps
    preference_settings: ModelSettingsOps
    tone_labels: object
    update_ops: UpdateOps
    def clear_successful_dangerous_calls(self) -> None: ...


class SlashControlPort(Protocol):
    ui: object
    prompt_ui: PromptUi | None
    permission_ops: PermissionOps
    async def compact_session_history(self, *, force: bool = False) -> bool: ...
    async def persist_runtime_state(self) -> None: ...
